[package]
name = "dynulo_radio"
version = "0.4.0"
authors = ["Dynulo"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# arma-rs = { git = "https://github.com/synixebrett/arma-rs", branch = "master" }
alto = "3.0"
arma-rs = { path = "../../arma-rs/core" }
lazy_static = "1.4"
log = "0.4"
rand = "0.7"
regex = "1.3"
reqwest = { version = "0.10", features = ["blocking"] }
rust-embed = "5.6.0"
simplemad = "0.9.0"
