[package]
name = "extension"
version = "0.1.0"
authors = ["Dynulo"]
edition = "2018"

[lib]
name = "dynulo_radio"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alto = "*"
arma-rs = { git = "https://github.com/synixebrett/arma-rs", branch = "master" }
lazy_static = "*"
libc = "*"
rand = "0.7"
reqwest = {version = "*", features = ["blocking"]}
simplemad = "0.9.0"
