[package]
name = "extension"
version = "0.1.0"
authors = ["Dynulo"]
edition = "2018"

[lib]
name = "dynulo_radio"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alto = "3.0"
arma-rs = { git = "https://github.com/synixebrett/arma-rs", branch = "master" }
lazy_static = "1.4"
libc = "0.2"
rand = "0.7"
reqwest = { version = "0.10", features = ["blocking"] }
rust-embed = "5.6.0"
simplemad = "0.9.0"
