[package]
name = "live_radio_cdylib"
version = "0.4.1"
authors = ["BrettMayson"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
arma-rs = { git = "https://github.com/BrettMayson/arma-rs", branch = "expirement" }
live_radio = { path = "../core" }

lazy_static = "1.4"
log = "0.4"
