name = "Live Radio"
prefix = "live_radio"
author = "Brett"
mainprefix = "z"
include = ["./include"]
files = ["mod.cpp", "live_radio.dll", "live_radio_x64.dll"]
template = "cba"

postbuild = ["!extension"]
releasebuild = ["@zip {{modname}}", "@zip {{key_name}}"]

[scripts.extension]
show_output = true
steps_windows = [
    "rustup target add i686-pc-windows-msvc",
    "cd extension && cargo build --release && cargo build --release --target=i686-pc-windows-msvc",
    "copy extension\\target\\release\\live_radio_cdylib.dll live_radio_x64.dll",
    "copy extension\\target\\i686-pc-windows-msvc\\release\\live_radio_cdylib.dll live_radio.dll",
]
steps_linux = [
    "echo \"Unable to build extension on Linux\""
]
