name = "ArmaRadio"
prefix = "radio"
author = "Brett"
mainprefix = "dynulo"
include = ["./include"]
files = ["mod.cpp", "dynulo_radio_x64.dll"]

postbuild = ["!extension"]
releasebuild = ["@zip {{modname}}", "@zip {{key_name}}"]

[scripts.extension]
show_output = true
steps_windows = [
    "cd extension && cargo build --release",
    "copy extension\\target\\release\\dynulo_radio.dll dynulo_radio_x64.dll"
]
steps_linux = [
    "echo \"Unable to build extension on Linux\""
]
