name = "Live Radio"
prefix = "live_radio"
author = "Brett"
mainprefix = "z"

[files]
include = [
    "live_radio.dll",
    "live_radio_x64.dll"
]

[hemtt.launch]
workshop = [
    "450814997", # CBA
    "463939057", # ACE
]

[hemtt.launch.noace]
workshop = [
    "450814997", # CBA
]
