name: Release

on:
  release:
    types:
      - published

jobs:
  build_extension:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Cargo Build
        run: cargo build --release --target x86_64-pc-windows-msvc
      - name: Rename DLL
        run: mv target/x86_64-pc-windows-msvc/release/live_radio.dll live_radio_x64.dll
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: live_radio_x64
          path: live_radio_x64.dll
          if-no-files-found: error
          retention-days: 30
  package:
    needs: build_extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: live_radio_x64
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Build
        run: hemtt release
      - uses: actions/upload-artifact@v4
        with:
          name: live_radio.zip
          path: "releases/live_radio-latest.zip"
      # Upload to GitHub
      - uses: softprops/action-gh-release@v1
        id: gh_release
        with:
          files: "releases/live_radio-latest.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Upload to Steam Workshop
      - run: unzip releases/live_radio-latest.zip -d ./unzipped
      - uses: arma-actions/workshop-upload@v1
        with:
          itemId: "2172022102"
          contentPath: "unzipped/@live_radio"
          changelog: ${{ steps.gh_release.outputs.url }}
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
