name: Release

on:
  release:
    types:
      - published

jobs:
  build_extension:
    strategy:
      matrix:
        arrays:
          [
            os: { tag: "windows-latest", target: "i686-pc-windows-msvc" },
            os: { tag: "windows-latest", target: "x86_64-pc-windows-msvc" },
          ]
    runs-on: ${{ matrix.arrays.os.tag }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install latest
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.arrays.os.target }}
          toolchain: stable
          default: true
      - name: Cargo Build
        run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arrays.os.target }}
          path: target/release/live_radio.dll
          if-no-files-found: error
          retention-days: 30
  package:
    needs: build_extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/download-artifact@v2
        with:
          name: x86_64-pc-windows-msvc
      - run: mv live_radio.dll live_radio_x64.dll
      - uses: actions/download-artifact@v2
        with:
          name: i686-pc-windows-msvc

      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Build
        run: hemtt release
      - uses: actions/upload-artifact@v2
        with:
          name: live_radio.zip
          path: "releases/live_radio-latest.zip"
      # Upload to GitHub
      - uses: softprops/action-gh-release@v1
        id: gh_release
        with:
          files: "releases/live_radio-latest.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Upload to Steam Workshop
      - run: unzip releases/live_radio-latest.zip -d ./unzipped
      - uses: arma-actions/workshop-upload@v1
        with:
          itemId: "2172022102" # Id of item to update
          contentPath: "unzipped/@live_radio"
          changelog: #{{ steps.gh_release.outputs.url }}
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
